services:
  auth-service:
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
  email-service:
    ports:
      - "5001:5000"
    depends_on:
      - rabbitmq
  clock-service:
    depends_on:
      - rabbitmq