networks:
  app-network:
    driver: bridge

include:
  - modules/clock/compose.yml
  - modules/auth/compose.yml
  - modules/email/compose.yml
  # - modules/image/compose.yml
  # - modules/scores/compose.yml
  # - modules/target/compose.yml
  

services:
  rabbitmq:
      image: rabbitmq:3.13-management-alpine
      container_name: webs5-rabbitmq
      hostname: webs5-rabbitmq
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        RABBITMQ_DEFAULT_USER: bigrabbit
        RABBITMQ_DEFAULT_PASS: bigrabbit
      networks:
      - app-network


