include:
  - modules/clock/compose.yml
  - modules/auth/compose.yml
  - modules/email/compose.yml
  - modules/scores/compose.yml
  - modules/target/compose.yml

services:
  rabbitmq:
      image: rabbitmq:3.13-management-alpine
      container_name: webs5-rabbitmq
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"
