services:
  db-auth:
    image: mysql:8.3.0
    restart: always
    container_name: db-auth
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth
      MYSQL_USER: user
      MYSQL_PASSWORD: magicman
    volumes:
      - db-auth-data:/var/lib/mysql
    ports:
      - 5050:3306
    networks:
      - app-network

  auth-service:
    build:
      context: .
      dockerfile: DOCKERFILE
    restart: always
    container_name: auth-service
    environment:
      PORT: 5000
      HOST: db-auth
      DB_DATABASE: auth
      DB_USER: user
      DB_PASSWORD: magicman
      DB_PORT: 3306
      AMQP_HOST: webs5-rabbitmq  
      AMQP_PORT: 5672
      AMQP_USER: bigrabbit           
      AMQP_PASSWORD: bigrabbit
      JWT_SECRET_KEY: secret_key_123
      QUEUE_RECEIVE_MAIL: mailConfirmedResponse
      QUEUE_SEND_MAIL: confirmMail
    depends_on:
      - db-auth
    networks:
      - app-network
  
volumes:
  db-auth-data:

# networks:
#   app-network:
#     external: true