services:
  clock-service:
    build:
      context: .
      dockerfile: DOCKERFILE
    restart: always
    container_name: clock-service
    environment:
      MONGO_URI: "mongodb://timer:timer@localhost:27017"
      MONGO_DB: "timerDb"
      MONGO_USER: "timer"
      MONGO_PASSWORD: "timer"

    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: clockDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: timer
      MONGO_INITDB_ROOT_PASSWORD: timer
