services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    restart: unless-stopped
    networks:
    - app-network
  
  email-service:
    build:
      context: .
      dockerfile: DOCKERFILE
    restart: always
    container_name: email-service
    environment:
      PORT: 5000
      HOST: 0.0.0.0
      AMQP_HOST: webs5-rabbitmq  
      AMQP_PORT: 5672
      AMQP_USER: bigrabbit           
      AMQP_PASSWORD: bigrabbit
      JWT_SECRET_KEY: secret_key_123
      QUEUE_RECEIVE_CONFIRMATION_REQUEST: mailConfirmed
      QUEUE_CONFIRMATION_RESPONSE: mailConfirmedResponse
      QUEUE_ENDSCORE_REQUEST: sendEndscoreEmail
    depends_on:
      - mailhog

# networks:
#   app-network:
#     external: true