services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    restart: unless-stopped
    networks:
      - mailhog-network

  email-service:
    build:
      context: .
      dockerfile: DOCKERFILE
    restart: always
    container_name: email-service
    environment:
      PORT: 5000
      HOST: 0.0.0.0
      AMQP_HOST: amqp://localhost
      JWT_SECRET_KEY: secret_key_123
      QUEUE_RECEIVE_CONFIRMATION_REQUEST: mailConfirmed
      QUEUE_CONFIRMATION_RESPONSE: mailConfirmedResponse
      QUEUE_ENDSCORE_REQUEST: sendEndscoreEmail
    depends_on:
      - mailhog

networks:
  mailhog-network:
    driver: bridge